import { GAME_WIDTH, GAME_HEIGHT, TEX } from '../config.js';

export default class MenuScene extends Phaser.Scene {
  constructor() { super('Menu'); }

  create() {
    // Temporary: prove textures generated by showing each one in a row.
    const keys = Object.values(TEX);
    keys.forEach((k, i) => {
      this.add.image(40 + (i % 5) * 80, 120 + Math.floor(i / 5) * 80, k);
    });
    this.add.text(GAME_WIDTH / 2, GAME_HEIGHT - 80, 'textures OK', {
      fontFamily: 'sans-serif', fontSize: '22px', color: '#ffffff',
    }).setOrigin(0.5);
  }
}
